### Language brain-score example API usage notebook

we will use this notebook as an end-user example of how LBS may be used, assuming most of the LBS functionality is already implemented (whereas it may not be).
In the meantime, the LBS interface will implement placeholder mock methods that either return `NotImplemented`, or otherwise return mock values consistent with types and dimensionality of what we would expect.

Step 1 towards this direction is to create a mock dataset matching a real-world dataset in size and dimensionality.

## Generate mock dataset

In [1]:
import numpy as np

The Pereira (2018) [[pdf]](https://www.nature.com/articles/s41467-018-03068-4.pdf) [[data]](https://evlab.mit.edu/sites/default/files/documents/index2.html) [[supp OSF]](https://osf.io/crwz7/) dataset consists of `627 = (384 + 243)` stimuli

In [2]:
# define the size and dimensionality of mock data to create
num_stimuli = 627
num_neuroid = 10_000
# now randomly generate the mock data
recorded_data = np.random.rand(num_stimuli, num_neuroid)
print(recorded_data[:5,:5])
recorded_data.shape

[[0.23155204 0.11057164 0.6666241  0.30420086 0.2103576 ]
 [0.96047531 0.41645043 0.50664239 0.24643677 0.96231829]
 [0.94900914 0.35849934 0.50397994 0.58011795 0.87096426]
 [0.18607884 0.06084626 0.72389155 0.71362688 0.41531549]
 [0.94437025 0.71091215 0.24287954 0.71237736 0.04157004]]


(627, 10000)

In [3]:
import random
stimuli = [''.join(random.sample('abcdefghijklmnopqrstuvwxiz'*20, 7)) for _ in recorded_data]
print(len(stimuli), stimuli[:4], '...')

627 ['tglqrpa', 'punqpik', 'joirgfp', 'gpzjzit'] ...


## Load Lbrainscore stuff

In [6]:
from pathlib import Path
import os

if '_path_fix_fuzzy_potato' in dir():
    print('this cell has already been executed! skipping.')
else:
    # we should normally be in the same directory as this notebook
    !pwd
    assert 'examples' in str(Path('.').resolve()), 'must execute this cell and below while in the "<lbs root>/examples" directory'

    # but we want to do the rest of the stuff from the parent directory, where the package langbrainscore is accessible
    os.chdir('..')

    # now verify that the package is in pwd
    !pwd
    print(*Path('.').resolve().glob('langbrainscore'))

    _path_fix_fuzzy_potato = None

this cell has already been executed! skipping.


In [19]:
%reload_ext autoreload
%autoreload 2
# import importlib

import langbrainscore as lbs
# importlib.reload('lbs')

In [20]:
mock_per_enc = lbs.interface.encoder.BrainEncoder()

TypeError: Can't instantiate abstract class BrainEncoder with abstract methods encode